### ISSUE TITLE
libiup.so: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by ivanceras** [cybergeek94/kiss-ui#19]
I always get this error, when trying to run the examples
I followed the installation of iup for
 
`3.13.0-53-generic #89-Ubuntu x86_64`
`libiup.so:` cannot open shared object file: No such file or directory

I know that when installing the iup library it transfer this file to that directory

`'libiup.so’ -> ‘/usr/lib64/libiup.so’`

and make sure it is there
```bash
/usr/lib64$ ls -la | grep libiup
-rwxr-xr-x  1 root root  826955 May 27 16:49 libiup.so
```

Luckily, I was able to solve it via
```bash
sudo ln -s /usr/lib64/libiup.so  /usr/lib/libiup.so
```

**Comment by cybergeek94** [comment]
Hmm, I downloaded the 3.13 64-bit libraries on my Linux Mint laptop and installed them, but they went to `/usr/lib`. I don't even have `/usr/lib64`.

**Comment by ivanceras** [comment]
That is strange, I think ubuntu is doing different from other linux distro
