### ISSUE TITLE
IupImage, IupImageRGB and IupImageRGBA are 3 different classes!

### ISSUE THREAD

**Issue by thelink2012** [cybergeek94/kiss-ui#26]
while the code thinks it's just "image", it is "image" "imagergb" and "imagergba"
See [iup_image.c](http://sourceforge.net/p/iup/iup/HEAD/tree/trunk/iup/src/iup_image.c#l690).

**Comment by cybergeek94** [comment]
Of course they had to make it like that. It's not hard to fix, but requires some refactoring of the way widgets are downcast to support multiple classnames.

**Comment by cybergeek94** [comment]
Haha, I decided to try to fix this one this weekend, and it looks like uBlock Origin updated to block Sourceforge.net entirely.
