### ISSUE TITLE
How can i access something inside a callback?

### ISSUE THREAD

**Issue by Andi-K** [cybergeek94/kiss-ui#27]
Hello! I need you help again.

I try to access a struct inside a callback.

My example code:
```
#[macro_use]
extern crate kiss_ui;

use kiss_ui::prelude::*;

use kiss_ui::button::Button;
use kiss_ui::container::Horizontal;
use kiss_ui::dialog::{self, AlertPopupBuilder};

pub struct Counter {
 pub value: u8,
}

impl<'a> Counter {
	fn new() -> Counter {
		Counter {value: 0}
	}
	
	fn inc(&mut self) {
		self.value += 1;
	}
}

#[macro_use]
extern crate lazy_static;
// cargo [dependencies]
// lazy_static = "0.1.*"
 
lazy_static! {
    static ref counter: Counter = Counter::new();
}
// works but is immutable 

// static mut counter: Counter = Counter::new();
// error: function calls in statics are limited to struct and enum constructors
// hmm isn't it a struct constructor?

fn main() {
//	let mut counter = Counter::new();

    kiss_ui::show_gui(||
        Dialog::new(
            Horizontal::new(
                children![               
                    Button::new()
                        .set_label("Message")
                        .set_onclick(show_counter_dialog),
                    Button::new()
                        .set_label("Close")
                        .set_onclick(close_dialog),
                ]
            )
            .set_elem_spacing_pixels(10)                   
        )
        .set_title("Button test!")
    )
}
 
// fn show_counter_dialog(_: Button, counter: Counter) { 
// =>  (expected a tuple with 1 elements, found one with 2 elements)
fn show_counter_dialog(_: Button) {
//	let mut counter = Counter::new();
// works, but i don't want to reset it 
	counter.inc();
    dialog::message_popup("Good job!", format!("You clicked the button {} times!", counter.value));
}
fn close_dialog(_: Button) -> CallbackStatus {
    println!("Closing dialog!");
    CallbackStatus::Close
}
```
I'm working on it since 3 days. :/
In PHP i just say something like "fn callback() use &counter {}".

Any Ideas how i get it done? 

Thank you in advance!

**Comment by cybergeek94** [comment]
This is actually a feature I've been meaning to document better! Since callbacks are `FnMut`, you can have the callback closure take ownership of an object and mutate it, keeping the same instance for as long as the callback is in use!

Here's your `main` function that we can make some tweaks to:

```rust
fn main() {
    // `mut` is still necessary here because of the semantics of closures
    let mut counter = Counter::new();

    // We changed the `show_counter_dialog` function into a closure
    // The `move` keyword tells the closure to take ownership of closed-over variables
    // In this case, `counter` is being moved into the closure.
    let show_counter_dialog = move |_| {
        counter.inc();
        dialog::message_popup("Good job!", format!("You clicked the button {} times!", counter.value));
    };

    // Now we move `show_counter_dialog` into this closure
    kiss_ui::show_gui(move ||
        Dialog::new(
            Horizontal::new(
                children![               
                    Button::new()
                        .set_label("Message")
                        // This is the same closure we created above.
                        .set_onclick(show_counter_dialog),
                    Button::new()
                        .set_label("Close")
                        .set_onclick(close_dialog),
                ]
            )
            .set_elem_spacing_pixels(10)                   
        )
        .set_title("Button test!")
    )
}
```

Here, `counter` will be preserved across invocations of `show_counter_dialog`.
In the future I might make it easier to tie user data to widgets so closures don't have to be used everywhere.

**Comment by Andi-K** [comment]
Ah `move` really  dos the magic, Thanks!
I already tried it but this error alienate me:
```
src/gui.rs:119:26: 119:39 error: use of moved value: `process_input`
src/gui.rs:119         	btn.set_onclick(process_input);
                       	                ^~~~~~~~~~~~~
note: `process_input` was previously moved here because it has type `[closure((kiss_ui::button::Button,))]`, which is non-copyable
```
But it only means i can't move it more then once.

If we add 
```
                    Button::new()
                        .set_label("reset")
                        .set_onclick(move |_| {counter.value = 0;}),

```
rustc say us this:
```
error: capture of moved value:  'counter'  ..
help: perhaps you meant to use 'clone()'?`
```
But i don't want to reset a cloned counter and forget it right after the change.

**Comment by thelink2012** [comment]
You perhaps want a reference counted cell. I had exactly the same doubt a while ago the answer I got on SO was pretty good. [Check it out][http://stackoverflow.com/questions/30153973/mutating-the-same-data-in-multiple-static-closures].

**Comment by cybergeek94** [comment]
This shows a definite need for some sort of storage that can either be freestanding or associated with a widget. I would probably prefer to implement this mostly in Rust and not just give arbitrary pointers to IUP; it would need much less unsafe code and wouldn't require converting lookup keys to C-strings.

The question becomes, then: how to implement it.

Consider a `DataStore` trait, implemented by `Widget` and a `storage::Global` struct.

* Create a typemap, where types are used as keys in a hashmap and return a reference to the same type:

```rust
pub trait DataStore {
    fn store<T: Any>(&self, val: T) -> Option<T>;
    fn load::<T: Any>(&self) -> Option<&T>;
}
```

* Key it by strings and let the user do the downcast:

```rust
pub trait DataStore {
    fn store<T: Any>(&self, key: &str, val: T) -> Option<T>;
    fn load(&self, key: &str) -> Option<&Any>;
}
```

* Or both:

```rust
pub trait DataStore {
    fn store<T: Any>(&self, key: &str, val: T) -> Option<T> ;
    fn load<T: Any>(&self, key: &str) -> Option<&T>;
}
```

Or combine the three APIs and make it possible to key by string, type, or both:

```rust
pub trait DataStore {
    fn store<T: Any>(&self, val: T) -> Option<T>;
    fn store_keyed<T: Any>(&self, key: &str, val: T) -> Option<Box<Any>>;

    fn load_key(&self, key: &str) -> Option<&Any>;
    fn load_type<T: Any>(&self) -> Option<&T>;
    fn load<T: Any>(&self, key: &str) -> Option<&T>;
}
```

Obviously there's some bikeshedding that can be done here. This would clash with `Widget::store` and `Widget::load` but I'm wondering if that should be implemented in terms of this API (it could potentially be slower and the semantics would be different), or be completely separate. Either way the existing methods will likely need to be renamed.

```rust
pub trait Widget {
    fn store_self(self, key: &str);
}

impl BaseWidget {
    fn load_self(key: &str) -> Option<Self>:
}
```

**Comment by thelink2012** [comment]
Keeping it simple, eh! _Combine_ wouldn't be a good idea. I liked the first approach, but I'm not sure if it's as scalable as the manual down casting one?

**Comment by cybergeek94** [comment]
The [Iron HTTP framework](http://ironframework.io/) uses a type-map to allow users to store data in the request object for moving in between links in the middleware chain. The pattern isn't all that dissimilar to KISS-UI callbacks, except KISS-UI doesn't thread callbacks for an obvious reason.

I don't think this API is so complex that it necessarily violates the KISS principle. However, I'm not sure if it's exactly *safe*, since a user could replace a stored value while there are still references to it. Making this take `&mut self` and removing the `Copy` impl on widgets should make it safe, which will also fix some other soundness issues that I just realized `Copy` introduced.

**Comment by Andi-K** [comment]
@thelink2012 thanks for your hint. I got new trouble but it points in the right direction.

Right now, i use [Piston's current](https://github.com/PistonDevelopers/current} (with a dirty fix  to use it on Rust stable)  and it looks like it covers all my needs.
At least my counter example works. 

@cybergeek94 
I have limited experience but i don't think a UI need nor should store Data.
Just make sure the user can easy access the own struct.
Why not just store a Pointer and pipe it to all callbacks as second argument? 
`.onclick( | btn: Button, &mut app: MyApp | { app.do_something(btn.get_name()) })` looks perfect for me

**Comment by cybergeek94** [comment]
I don't think Piston-current works as a long-term measure because you cannot, for example, put something into it in one callback and then pull it out in another; the first callback would have exited and the pointer that Piston-current stored is now junk. It may work for trivial cases but I'd rather have a more complete, safe, and intuitive solution.

Being able to store data in the KISS-UI context would enable this.

**Comment by cybergeek94** [comment]
After giving it some thought, I think the best solution would be a typemap like what Iron does. If a user needs to store more than one of the same type, they can wrap it in a newtype. Unlike the `typemap` crate, the user wouldn't have to implement any special traits for the newtype, it would just have to be `Any`, which all types automatically implement if they are `'static`.

Now, I'm having trouble making the API design work without creating multiple mutable aliases to either the typemap or the data stored inside. Each load would have to immutably borrow the typemap and then mutably borrow the type. This implies some heavy usage of `RefCell`, including exposing some of those details to user code, like the `RefMut` RAII guard. 

This may seem like a no-brainer but keep in mind that some state changes on widgets can trigger other callbacks, which means we can have user code running under the stack frames of others. So one callback could borrow the typemap and then make some changes, causing another callback to run which could also try to borrow the same typemap before the first callback has returned. This would cause a panic in `RefCell::borrow_mut()` which would probably only serve to confuse the user.

**Comment by Andi-K** [comment]
> I don't think Piston-current works as a long-term measure because you cannot, for example, put something into it in one callback and then pull it out in another; the first callback would have exited and the pointer that Piston-current stored points to junk. It may work for trivial cases but I'd rather have a more complete, safe, and intuitive solution.

Well it's just safe if you take a bit care, but in my project there wasn't any problem.

My project isn't ready to use but i'll upload it. So you can take a look.

> Now, I'm having trouble making the API design work...
> We could avoid some panics if RefCell::borrow_state() was stable...

My 2 cents: Just wait! Sometimes to time works for you ;)
KISS-UI just covers the basics, right now. I don't think someone use it for complex tasks and really needs this feature asap.
Piston-current may isn't the best solution, but a simple solution and ready to use.

**Comment by cybergeek94** [comment]
Why do you use `Box` so much? You don't need to put any of the widget types behind a box.

**Comment by Andi-K** [comment]
That's right, i forgot to remove it.
I got `main has overflowed its stack` panics as i played around with HashMap.
Needless to say the real cause wasn't there where the panics appear. And i don't really need the HashMaps anyway.
But my `widget_by_name!` macro is useful. Don't you think so, too?

**Comment by cybergeek94** [comment]
The macro looks good but I think I can combine fetching and downcasting (since you usually don't want to use `BaseWidget`anyways) to eliminate at least one `expect()`call.

**Comment by cybergeek94** [comment]
So, yeah, it looks like storage would be a superfluous feature, since `thread_local!` works just fine for most purposes and you can also move `Rc` clones into new callbacks.

I'm going to close this issue since I think the problem has been resolved, and open a new one about documenting how to move data into callback closures or use `thread_local!`.
