### ISSUE TITLE
Panic in textbox_test example

### ISSUE THREAD

**Issue by lxn** [cybergeek94/kiss-ui#35]
On exit of `show_alert_message` `text` gets dropped and its `refcount` underflows.

This message is printed to the console:
```
thread '<main>' panicked at 'arithmetic operation overflowed', C:\devel\Rust\kiss-ui\src\widget.rs:213
fatal runtime error: Could not unwind stack, error = 5
```

**Comment by Andi-K** [comment]
I fixed it, the PR is waiting.

See https://github.com/cybergeek94/kiss-ui/pull/34

**Comment by lxn** [comment]
Thanks :)
