### ISSUE TITLE
Getting "unauthorized" by rust-ci.org using 2d35878's secure token

### ISSUE THREAD

**Issue by comwt** [cybergeek94/kiss-ui#39]
System:  Arch
Linux lpt1 4.0.7-2-ARCH #1 SMP PREEMPT Tue Jun 30 07:50:21 UTC 2015 x86_64 GNU/Linux

Also tried this from a Debian Jessie container with the same results...

$ curl http://www.rust-ci.org/artifacts/put?t=$RUSTCI_TOKEN -v
*   Trying 151.236.11.197...
* Connected to www.rust-ci.org (151.236.11.197) port 80 (#0)
> GET /artifacts/put?t=LBCp1Sz9ofbWbyN0GtpbICw0CZW4Hw+iOrw1zYJInHtS4/dJjrHjKJqy8aRB2rBPwc7Mt8sSgRVirj90XA0UwDD8nennQB9m8diXYOm03Itj+/2iKJCMchM8r/cNmaYeHelYcEHzLHykNaWSZ08gj0Bz3hDYVMI4ey4h1CpIdwM= HTTP/1.1
> Host: www.rust-ci.org
> User-Agent: curl/7.43.0
> Accept: */*
> 
< HTTP/1.1 401 UNAUTHORIZED
< Server: nginx/1.5.6
< Content-Type: text/html; charset=utf-8
< cache-control: max-age=0
< Content-Length: 12
< Accept-Ranges: bytes
< Date: Wed, 08 Jul 2015 05:47:17 GMT
< X-Varnish: 1493651606
< Via: 1.1 varnish
< Connection: keep-alive
< age: 0
< X-Cache: MISS
< 
* Connection #0 to host www.rust-ci.org left intact
Unauthorized

**Comment by cybergeek94** [comment]
The only reason one would have to invoke Rust CI is if they were updating the documentation, which is now hosted on Github Pages. That line actually needs to be deleted from `.travis.yml`.
