### ISSUE TITLE
container::Absolute lacks a constructor function

### ISSUE THREAD

**Issue by Zarathustra30** [cybergeek94/kiss-ui#40]
...and I'm not *quite* sure how to use it without one.

**Comment by cybergeek94** [comment]
Ah yeah, `Absolute` was meant to just be a stub until I added a way to set the position of a widget in its container, since it doesn't arrange its children on its own. I guess I forgot to make it constructible, I'll fix that shortly.

**Comment by cybergeek94** [comment]
Closed by f4ab6b3194d673964e23022b7fd8fbd2d01bc160, have a look!
