### ISSUE TITLE
Don't unconditionally link gtk-3 on not windows

### ISSUE THREAD

**Issue by crumblingstatue** [cybergeek94/kiss-ui#9]
The `iup` package on my system links to gtk-2, but kiss-ui unconditionally tries to link to gtk-3, making the build fail.

One possible solution to this letting the user decide whether he wants to link to gtk-3 through a cargo feature. But this might not be a very ideal solution.

Here is what I cooked up:
```diff
diff --git a/Cargo.toml b/Cargo.toml
index 6f005ea..c9c6b0d 100644
--- a/Cargo.toml
+++ b/Cargo.toml
@@ -5,6 +5,10 @@ authors = ["Austin Bonander <austin.bonander@gmail.com>"]
 
 [dependencies.iup-sys]
 path = "iup-sys/"
+features = [""]
 
 [dependencies]
 libc = "*"
+
+[features]
+no-gtk3 = ["iup-sys/no-gtk3"]
diff --git a/iup-sys/Cargo.toml b/iup-sys/Cargo.toml
index 805e976..74a45e1 100644
--- a/iup-sys/Cargo.toml
+++ b/iup-sys/Cargo.toml
@@ -8,3 +8,6 @@ build = "build.rs"
 
 [dependencies]
 libc = "*"
+
+[features]
+no-gtk3 = []
diff --git a/iup-sys/build.rs b/iup-sys/build.rs
index 464af6c..ceee847 100644
--- a/iup-sys/build.rs
+++ b/iup-sys/build.rs
@@ -1,7 +1,7 @@
 fn main() {
     add_link("iup");
 
-    if cfg!(not(windows)) {
+    if cfg!(not(windows)) && std::env::var_os("CARGO_FEATURE_NO_GTK3").is_none(){
         add_link("gtk-3"); 
     }
 }

```

**Comment by cybergeek94** [comment]
Actually, it looks like the IUP driver is linked to a specific version of GTK+ when it was compiled. If you try to link GTK+2.0 on a system with IUP linked with GTK+3.0 installed, you get the following error:

> Gtk-ERROR **: GTK+ 2.x symbols detected. Using GTK+ 2.x and GTK+ 3 in the same process is not supported

So that line can probably just be deleted. I thought I needed it to fix some build errors in Travis-CI but it appears I was just using the wrong IUP download.

**Comment by cybergeek94** [comment]
We'll see how this build turns out: https://travis-ci.org/cybergeek94/kiss-ui/builds/63223596

Now comes the only problem with working during the day: Travis takes forever to boot. :laughing:

**Comment by cybergeek94** [comment]
The build for #10 passed, looks like the fix is to let IUP choose the GTK+ version.
